name: Continuous integration

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Build
        run: mvn clean compile

      - name: Test
        run: mvn test

      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'

      - name: Deploy
        run: mvn -B deploy -Psign
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: spring-kafka-streams
          path: ${{ github.workspace }}/spring-kafka-streams/target/spring-kafka-streams-*.jar

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: spring-kafka-streams-test
          path: ${{ github.workspace }}/spring-kafka-streams-test/target/spring-kafka-streams-test-*.jar
